### ISSUE TITLE
No results binding datagrid to inline datasource 

### ISSUE THREAD

**Issue by iAlexanderMoon** [DevExpress/DevExtreme.AspNet.TagHelpers#10]
Hello, I've gone through the DevExtreme ASP.NET TagHelpers - Getting Started and waded through the samples and have my a gridview loading with using the load-action setting:
```
<dx-data-grid column-auto-width="true">
    <datasource controller="Work" load-action="GridData" />
</dx-data-grid>
```
I expected that using inline data I would be able to set the model data in the controller and bind the grid to it on the server:
```
@model IEnumerable<QueryModel>
<dx-data-grid column-auto-width="true">
    <datasource items="Model"  />
    <column datafield="Total" />
</dx-data-grid>
```
The resultant page source has a DevExpress.data.ArrayStore with my data, however no data is visible on my grid. Is this a bug or am I missing something?

**Comment by IlyaKhD** [comment]
Hi Alexander!
In v15.2.4-rc1-build1 inline data items (set as `<datasource items=... />`) are rendered in *lowerCamelCase*. You can try to set the column `datafield` attribute to `total` instead of `Total` to overcome the problem.

This was fixed, and the fix will be included to the next release, see issue https://github.com/DevExpress/DevExtreme.AspNet.TagHelpers/issues/5.

**Comment by iAlexanderMoon** [comment]
That fixed it thanks.

**Comment by AlekseyMartynov** [comment]
FYI default JSON serialization settings have been changed in ASP.NET Core 1.0. Starting with 15.2.10, both `<datasource items=...>` and `<datasource controller=...>` use lower camel case naming conventions by default.

Check [this ASP.NET Core announcement](https://github.com/aspnet/Announcements/issues/194) for details.
