### ISSUE TITLE
Globalize dependency preventing compile RC2

### ISSUE THREAD

**Issue by Se3ker** [DevExpress/DevExtreme.AspNet.TagHelpers#28]
Issue explained here:
https://github.com/DevExpress/bower-devextreme/issues/9

**Comment by AlekseyMartynov** [comment]
The issue occurs because the .NET Core compiler tries to process C# files from the globalize package. The solution is to exclude certain locations (such as wwwroot, node_modules, bower_components) from compilation. Check [this block](https://github.com/DevExpress/DevExtreme.AspNet.TagHelpers/blob/0193f3ac6625a12c213a3e7734df50e2f9e2efef/Samples/project.json#L72-L75) of our sample project.json file.
